### ISSUE TITLE
Unhandled rejection Error: Command 'say' already has a handler from plugin 'tennu-say/plugin.js'

### ISSUE THREAD

**Issue by LordWingZero** [Tennu/tennu#60]
Is there a way that we could modify Tennu to take the last defined handler for a command instead of blowing up?

Its already set up to where you have to add your required roles in the plugins array BEFORE you add the plugin that needs it. So it doesnt seem to much of a stretch to have overrides be defined after the plugin you want to override.

I have created a more advanced say plugin but unfortunately, if people want to use it they have to remove tennu-control.

**Comment by Havvy** [comment]
Sure. For the `command-ignore-list`, modify it such that if it takes a string, it disables that command across all plugins. But if it takes an array, disable the command listed in the first element in all plugins listed in the rest of the elements.

I'm not going to be able to make that modification until around Thursday though, but if you want to take your hand at it, it's all in the commands plugin - just move the current ignore command logic to the `on` handler in subscribe. You'll see the plugin name in the metadata in that function too.

**Comment by LordWingZero** [comment]
That seems really confusing for users since one wouldn't expect other plugins commands to suddenly start working, nor would they expect that any element after the first is now referring to a command inside a plugin. I propose one of the following:

**A new config option, this wont break backwards compatibility**

```javascript
"ignore-plugin-commands": { "control":["say", "quit"] }
```

This would be just as easy to implement as your proposed solution,

**Or my personally preferred option... just replace the  throw with this:**

```javascript
 if (commandName in registry) {
    const warnMessage = format("Command '%s' already has a handler from plugin '%s', '%s' will override and be executed instead.", commandName, registry[commandName].plugin, plugin);
    client.warn("PluginCommands", warnMessage);
}
```

This wont break anything because in its current state, tennu wont even start.

**Comment by Havvy** [comment]
I should have said "modify it such that if an element in the list is a" instead of the whole option itself being a String.

Basically, we have today `command-ignore-list: ["say", "quit"]` which would ignore the commands today completely, though it doesn't actually let you have two plugins with the same command. That itself is a bug. My proposal is to make it `command-ignore-list: [["say", "control"], "quit"]` which would make `"say"` be ignored in the "control" plugin, and "quit" ignored in all plugins. It is backwards compatible with the current format.

If I wanted to eschew backwards compatibility, I would make it an object as per your first code block in the previous post, with `*` ignoring everywhere as it currently does. This is an option.

Replacing the error with a warning is not going to happen.
